package dev.tachyonscript.security;

public enum SecurityCategory {
    COMMAND_INJECTION, PRIVILEGE_ESCALATION, PERMISSION_BYPASS,
    SSRF, DYNAMIC_URL, UNSAFE_REDIRECT, PATH_TRAVERSAL, UNSAFE_FILE_OPERATION,
    SQL_INJECTION, DYNAMIC_SQL, CREDENTIAL_EXPOSURE, DATA_EXFILTRATION,
    UNBOUNDED_LOOP, TASK_EXPLOSION, RECURSIVE_SCHEDULING, EVENT_SPAM,
    OBFUSCATION, UNKNOWN_CAPABILITY, DEPENDENCY_BLOCKED, ADMINISTRATIVE_ACTION
}
