#!/usr/bin/env python3
"""
Generates most of the TachyonScript standard library from compact API specifications.

A specification line declares one type, property, function or event: its script signature,
its documentation, its threading and side effects, and the Java code implementing it on
Paper. From the specifications (tools/stdlib-gen/spec/*.api) this script writes

* the Bukkit-free declarations      tachyon-stdlib/.../stdlib/generated/<Area>Api.java
* the generated types               tachyon-stdlib/.../stdlib/generated/GeneratedTypes.java
* the bindings of "core" areas      tachyon-stdlib/.../stdlib/generated/<Area>Bindings.java
* the Paper bindings                tachyon-platform-paper/.../platform/paper/generated/<Area>Bindings.java
* the constant tables of keyed types (Material, Sound, ...), extracted from the Paper API sources,
                                    tachyon-stdlib/src/main/resources/dev/tachyonscript/stdlib/keys/<type>.txt

The generated files are committed: building TachyonScript never needs Python. Run this script
after editing a specification (the constant tables need the Paper API sources, e.g. from the
paper-api sources jar):

    python tools/stdlib-gen/generate.py --paper-sources <folder with org/bukkit/...>

Without --paper-sources the existing constant tables are kept.

Specification format (one directive per line; lines starting with # are comments):

    import <java.Class>                     Java import for the generated Paper bindings
    area <Name> [core]                      following declarations belong to this area; core areas
                                            are implemented without a server (JDK only)
    type <Name> [extends A,B] [storable] [keyed=<keys>] [lookup=<lookup>] [core] = <java.Class> : <doc>
        codec: <Java expression of a dev.tachyonscript.api.storage.Codec>
    prop <Owner>.<name>: <Type> [rw] [<threading>] [<effect>] : <doc>
        get: <Java expression>              $ is the receiver
        set: <Java statement>               v is the new value
    fn <Owner>.<name>(<a>: <T>, ...)[: <R>] [<threading>] [<effect>] : <doc>
        do: <Java expression, statement, or { block }>
    event <name> = <java.EventClass> [cancellable] [extends <Type>] [<threading>] : <doc>
        var <name>: <Type> = <Java expression> : <doc>
        prop / fn ...                       members of the event object (the owner is implied)
    ...
        ex: <script example>                (\\n for new lines) for the declaration above
        details: <longer documentation>

An owner that is not a type (server, math, ...) declares a global property or function; a
global function named like a type (ItemStack, Vector) reads like a constructor in scripts.
Threading: entity | region | global | async, optionally naming the parameter that decides the
owning thread: entity(target). Effects: pure | reads | modifies | io.
Keys: enum:<path.java>[#Nested] | fields:<path.java>:<factory method> | list:NAME,NAME
Lookups (how a key finds the Paper object): enum | keyed-enum | registry:<RegistryKey constant>
"""

import argparse
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Optional

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SPEC_DIR = os.path.join(os.path.dirname(__file__), 'spec')
STDLIB_PACKAGE = 'dev.tachyonscript.stdlib.generated'
PAPER_PACKAGE = 'dev.tachyonscript.platform.paper.generated'
STDLIB_OUT = os.path.join(ROOT, 'tachyon-stdlib', 'src', 'main', 'java', *STDLIB_PACKAGE.split('.'))
PAPER_OUT = os.path.join(ROOT, 'tachyon-platform-paper', 'src', 'main', 'java', *PAPER_PACKAGE.split('.'))
KEYS_OUT = os.path.join(ROOT, 'tachyon-stdlib', 'src', 'main', 'resources', 'dev', 'tachyonscript', 'stdlib', 'keys')
SINCE = '0.2.0'
HEADER = '// Generated by tools/stdlib-gen/generate.py from tools/stdlib-gen/spec. Do not edit.\n'
SUPPRESS = '@SuppressWarnings({"unchecked", "rawtypes", "deprecation", "removal"})'

JAVA_KEYWORDS = set('''abstract assert boolean break byte case catch char class const continue default do double else
enum extends final finally float for goto if implements import instanceof int interface long native new package private
protected public return short static strictfp super switch synchronized this throw throws transient try void volatile
while true false null var record yield'''.split())
RESERVED_LOCALS = {'a', 'b', 'v', 'self', 'ctx'}


class SpecError(Exception):
    pass


def fail(where, message):
    raise SpecError(f'{where}: {message}')


# ============================================================================ types

# name: (Types constant, Java type, argument accessor, representation)
PRIMITIVES = {
    'int': ('Types.INT', 'int', 'getInt', 'INT'),
    'long': ('Types.LONG', 'long', 'getLong', 'LONG'),
    'float': ('Types.FLOAT', 'float', 'getFloat', 'FLOAT'),
    'double': ('Types.DOUBLE', 'double', 'getDouble', 'DOUBLE'),
    'bool': ('Types.BOOL', 'boolean', 'getBool', 'BOOL'),
    'Duration': ('Types.DURATION', 'long', 'getLong', 'LONG'),
    'Instant': ('Types.INSTANT', 'long', 'getLong', 'LONG'),
}
BOXES = {'int': 'Integer', 'long': 'Long', 'float': 'Float', 'double': 'Double', 'bool': 'Boolean',
         'Duration': 'Long', 'Instant': 'Long'}
SHAPES = {'INT': 'OfInt', 'LONG': 'OfLong', 'FLOAT': 'OfFloat', 'DOUBLE': 'OfDouble', 'BOOL': 'OfBool',
          'VOID': 'OfVoid', 'REF': 'OfRef'}


@dataclass
class TypeInfo:
    name: str
    constant: str                 # Java expression of the ClassType
    java: Optional[str]           # Java class of values (None: not bound here)
    new: bool = True              # declared by the generator (False: hand-written)
    supertypes: list = field(default_factory=list)
    storable: bool = False
    keyed: Optional[str] = None
    lookup: Optional[str] = None
    codec: Optional[str] = None
    core: bool = False
    doc: str = ''
    details: str = ''
    where: str = ''
    examples: list = field(default_factory=list)


TYPES = {}


def builtin(name, constant, java, core=True):
    TYPES[name] = TypeInfo(name, constant, java, new=False, core=core)


# Types of the language and of the hand-written standard library.
builtin('string', 'Types.STRING', 'String')
builtin('any', 'Types.ANY', 'Object')
builtin('Error', 'Types.EXCEPTION', 'dev.tachyonscript.api.value.ScriptFailure')
builtin('Component', 'Types.COMPONENT', 'net.kyori.adventure.text.Component', core=False)
builtin('UUID', 'MinecraftTypes.UUID', 'java.util.UUID')
builtin('Task', 'MinecraftTypes.TASK', 'dev.tachyonscript.api.value.ScriptTask')
for _name, _constant, _java in [
    ('CommandSender', 'COMMAND_SENDER', 'org.bukkit.command.CommandSender'),
    ('World', 'WORLD', 'org.bukkit.World'),
    ('Location', 'LOCATION', 'org.bukkit.Location'),
    ('Entity', 'ENTITY', 'org.bukkit.entity.Entity'),
    ('LivingEntity', 'LIVING_ENTITY', 'org.bukkit.entity.LivingEntity'),
    ('OfflinePlayer', 'OFFLINE_PLAYER', 'org.bukkit.OfflinePlayer'),
    ('Player', 'PLAYER', 'org.bukkit.entity.Player'),
    ('Block', 'BLOCK', 'org.bukkit.block.Block'),
    ('GameMode', 'GAME_MODE', 'org.bukkit.GameMode'),
    ('Cancellable', 'CANCELLABLE', 'org.bukkit.event.Cancellable'),
    ('PlayerJoinEvent', 'PLAYER_JOIN_EVENT', 'org.bukkit.event.player.PlayerJoinEvent'),
    ('PlayerQuitEvent', 'PLAYER_QUIT_EVENT', 'org.bukkit.event.player.PlayerQuitEvent'),
    ('EntityDeathEvent', 'ENTITY_DEATH_EVENT', 'org.bukkit.event.entity.EntityDeathEvent'),
    ('PlayerDeathEvent', 'PLAYER_DEATH_EVENT', 'org.bukkit.event.entity.PlayerDeathEvent'),
    ('PlayerChatEvent', 'PLAYER_CHAT_EVENT', 'io.papermc.paper.event.player.AsyncChatEvent'),
    ('PlayerMoveEvent', 'PLAYER_MOVE_EVENT', 'org.bukkit.event.player.PlayerMoveEvent'),
    ('BlockBreakEvent', 'BLOCK_BREAK_EVENT', 'org.bukkit.event.block.BlockBreakEvent'),
    ('EntityDamageEvent', 'ENTITY_DAMAGE_EVENT', 'org.bukkit.event.entity.EntityDamageEvent'),
]:
    builtin(_name, 'MinecraftTypes.' + _constant, _java, core=False)
# Supertypes of hand-written types, for "is this type cancellable?" checks.
TYPES['Player'].supertypes = ['LivingEntity', 'CommandSender', 'OfflinePlayer']
TYPES['LivingEntity'].supertypes = ['Entity']
for _event in ['EntityDeathEvent', 'PlayerChatEvent', 'PlayerMoveEvent', 'BlockBreakEvent', 'EntityDamageEvent']:
    TYPES[_event].supertypes = ['Cancellable']
TYPES['PlayerDeathEvent'].supertypes = ['EntityDeathEvent']


def upper_snake(name):
    name = name.replace('.', '_')
    out = re.sub(r'(?<=[a-z0-9])([A-Z])', r'_\1', name)
    return re.sub(r'__+', '_', out).upper()


def is_subtype(name, ancestor):
    if name == ancestor:
        return True
    info = TYPES.get(name)
    return info is not None and any(is_subtype(s, ancestor) for s in info.supertypes)


def split_top(text, separator=','):
    """Splits at separators outside <...> and (...)."""
    parts, depth, current = [], 0, ''
    for c in text:
        if c in '<(':
            depth += 1
        elif c in '>)':
            depth -= 1
        if c == separator and depth == 0:
            parts.append(current.strip())
            current = ''
        else:
            current += c
    if current.strip():
        parts.append(current.strip())
    return parts


def matching(text, start):
    """Index of the bracket closing the one at text[start]."""
    opener = text[start]
    closer = {'(': ')', '<': '>', '{': '}'}[opener]
    depth = 0
    for i in range(start, len(text)):
        if text[i] == opener:
            depth += 1
        elif text[i] == closer:
            depth -= 1
            if depth == 0:
                return i
    raise SpecError('Unbalanced brackets: ' + text)


def parse_type_text(text, i=0):
    """Reads a script type at text[i:]; returns (type text, index after it)."""
    while i < len(text) and text[i] == ' ':
        i += 1
    if text.startswith('function(', i):
        close = matching(text, i + len('function'))
        end = close + 1
        j = end
        while j < len(text) and text[j] == ' ':
            j += 1
        if j < len(text) and text[j] == ':':
            _, end = parse_type_text(text, j + 1)
        return text[i:end].strip(), end
    m = re.match(r'[A-Za-z_][A-Za-z0-9_]*', text[i:])
    if not m:
        raise SpecError('Expected a type at: ' + text[i:])
    end = i + m.end()
    if end < len(text) and text[end] == '<':
        end = matching(text, end) + 1
    if end < len(text) and text[end] == '?':
        end += 1
    return text[i:end], end


class TypeRef:
    """A script type used in a specification."""

    def __init__(self, text):
        self.text = text.strip()

    @property
    def nullable(self):
        return self.text.endswith('?') and not self.text.startswith('function(')

    @property
    def base(self):
        return self.text[:-1] if self.nullable else self.text

    def check(self, where):
        try:
            self.constant()
            if self.base != 'void':
                self.java()
        except SpecError as e:
            fail(where, str(e))

    def constant(self):
        if self.nullable:
            return 'Types.nullable(' + TypeRef(self.base).constant() + ')'
        b = self.base
        if b == 'void':
            return 'Types.VOID'
        if b in PRIMITIVES:
            return PRIMITIVES[b][0]
        if b.startswith('List<'):
            return 'Types.list(' + TypeRef(b[5:-1]).constant() + ')'
        if b.startswith('Map<'):
            k, v = split_top(b[4:-1])
            return 'Types.map(' + TypeRef(k).constant() + ', ' + TypeRef(v).constant() + ')'
        if b.startswith('function('):
            close = matching(b, len('function'))
            params = split_top(b[len('function('):close])
            rest = b[close + 1:].strip()
            result = TypeRef(rest[1:]) if rest.startswith(':') else TypeRef('void')
            return ('Types.function(java.util.List.of(' + ', '.join(TypeRef(p).constant() for p in params)
                    + '), ' + result.constant() + ')')
        if b in TYPES:
            return TYPES[b].constant
        raise SpecError('Unknown type ' + b)

    def representation(self):
        if self.nullable:
            return 'REF'
        if self.base == 'void':
            return 'VOID'
        if self.base in PRIMITIVES:
            return PRIMITIVES[self.base][3]
        return 'REF'

    def shape(self):
        return SHAPES[self.representation()]

    def java(self):
        """Java type of values of this type on the platform."""
        b = self.base
        if b in PRIMITIVES:
            return BOXES[b] if self.nullable else PRIMITIVES[b][1]
        if b.startswith('List<'):
            return 'java.util.List<Object>'
        if b.startswith('Map<'):
            return 'java.util.Map<Object, Object>'
        if b.startswith('function('):
            return 'dev.tachyonscript.api.natives.ScriptFunction'
        if b in TYPES and TYPES[b].java:
            return TYPES[b].java
        raise SpecError('Type ' + b + ' has no Java class')

    def read(self, index):
        """Java expression reading argument {index}."""
        if not self.nullable and self.base in PRIMITIVES:
            return 'a.' + PRIMITIVES[self.base][2] + '(' + str(index) + ')'
        java = self.java()
        if java == 'Object':
            return 'a.getRef(' + str(index) + ')'
        if java == 'String':
            return 'a.getString(' + str(index) + ')'
        return '(' + java + ') a.getRef(' + str(index) + ')'


# ============================================================================ declarations

@dataclass
class Param:
    name: str
    type: TypeRef


@dataclass
class Member:
    kind: str                     # prop | fn
    owner: Optional[str]          # type name; None for globals
    name: str                     # simple name for members, qualified name for globals
    params: list
    type: TypeRef                 # property type or return type
    where: str
    mutable: bool = False
    threading: str = 'ANY'
    thread_param: Optional[str] = None
    effect: Optional[str] = None
    doc: str = ''
    details: str = ''
    get: Optional[str] = None
    set: Optional[str] = None
    body: Optional[str] = None
    examples: list = field(default_factory=list)
    constant: str = ''


@dataclass
class EventVar:
    name: str
    type: TypeRef
    expr: str
    doc: str


@dataclass
class Event:
    name: str
    java: str
    type_name: str
    where: str
    cancellable: bool = False
    threading: str = 'GLOBAL'
    doc: str = ''
    details: str = ''
    vars: list = field(default_factory=list)
    examples: list = field(default_factory=list)
    constant: str = ''


@dataclass
class Area:
    name: str
    core: bool
    members: list = field(default_factory=list)
    events: list = field(default_factory=list)
    types: list = field(default_factory=list)


FLAGS_THREADING = {'entity': 'ENTITY', 'region': 'REGION', 'global': 'GLOBAL', 'async': 'ASYNC'}
FLAGS_EFFECT = {'pure': 'PURE', 'reads': 'READS_WORLD', 'modifies': 'MODIFIES_WORLD', 'io': 'IO'}


def split_doc(text):
    if ' : ' in text:
        head, doc = text.split(' : ', 1)
        return head.strip(), doc.strip()
    return text.strip(), ''


def parse_member(keyword, text, where, owner_override=None):
    head, doc = split_doc(text)
    m = re.match(r'([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*)', head)
    if not m:
        fail(where, 'expected a name: ' + head)
    path = m.group(1)
    rest = head[m.end():]
    params = []
    if keyword == 'fn':
        if not rest.startswith('('):
            fail(where, 'expected ( after the function name')
        close = matching(rest, 0)
        for p in split_top(rest[1:close]):
            if ':' not in p:
                fail(where, 'parameter without type: ' + p)
            pname, ptype = p.split(':', 1)
            pname = pname.strip()
            if pname in JAVA_KEYWORDS or pname in RESERVED_LOCALS:
                fail(where, 'parameter name ' + pname + ' is reserved in the generated Java')
            params.append(Param(pname, TypeRef(ptype)))
        rest = rest[close + 1:]
    type_text = 'void'
    rest = rest.strip()
    if rest.startswith(':'):
        type_text, end = parse_type_text(rest, 1)
        rest = rest[end:]
    elif keyword == 'prop':
        fail(where, 'a property needs a type')
    words = rest.split()
    static = 'static' in words
    if owner_override is not None:
        owner, name = owner_override, path
    elif '.' in path and path.rsplit('.', 1)[0] in TYPES and not static:
        owner, name = path.rsplit('.', 1)
    else:
        owner, name = None, path
    member = Member(keyword, owner, name, params, TypeRef(type_text), where, doc=doc)
    for word in words:
        flag = re.match(r'^(entity|region|global|async)(?:\((\w+)\))?$', word)
        if word == 'static':
            continue
        if word == 'rw':
            member.mutable = True
        elif flag:
            member.threading = FLAGS_THREADING[flag.group(1)]
            member.thread_param = flag.group(2)
        elif word in FLAGS_EFFECT:
            member.effect = FLAGS_EFFECT[word]
        else:
            fail(where, 'unknown flag ' + word)
    member.type.check(where)
    for p in params:
        p.type.check(where)
    if member.thread_param is not None and member.thread_param not in [p.name for p in params]:
        fail(where, 'threading parameter ' + member.thread_param + ' is not a parameter')
    if member.threading in ('ENTITY', 'REGION') and owner is None and member.thread_param is None:
        fail(where, 'a global needs a parameter for ' + member.threading.lower() + ' threading')
    if keyword == 'prop' and member.thread_param is not None:
        fail(where, 'properties cannot name a threading parameter')
    return member


def parse_type_line(text, where, area):
    head, doc = split_doc(text[5:])
    if ' = ' not in head:
        fail(where, 'a type needs = <java class>')
    decl, java = head.split(' = ', 1)
    words = decl.split()
    name = words[0]
    if name in TYPES:
        fail(where, 'type ' + name + ' is already declared')
    info = TypeInfo(name, 'GeneratedTypes.' + upper_snake(name), java.strip(), doc=doc, where=where)
    i = 1
    while i < len(words):
        word = words[i]
        if word == 'extends':
            i += 1
            info.supertypes = [s for s in words[i].split(',') if s]
        elif word == 'storable':
            info.storable = True
        elif word == 'core':
            info.core = True
        elif word.startswith('keyed='):
            info.keyed = word[6:]
        elif word.startswith('lookup='):
            info.lookup = word[7:]
        else:
            fail(where, 'unknown type option ' + word)
        i += 1
    for s in info.supertypes:
        if s not in TYPES:
            fail(where, 'unknown supertype ' + s + ' (declare supertypes first)')
    if bool(info.keyed) != bool(info.lookup):
        fail(where, 'a keyed type needs both keyed= and lookup=')
    TYPES[name] = info
    if area is not None:
        area.types.append(info)
    return info


def read_specs():
    areas, imports = [], []
    files = sorted(f for f in os.listdir(SPEC_DIR) if f.endswith('.api'))
    for spec in files:
        with open(os.path.join(SPEC_DIR, spec), encoding='utf-8') as source:
            lines = source.read().split('\n')
        area = None
        target = None          # declaration receiving indented lines
        event = None           # event receiving indented var/prop/fn lines
        for number, raw in enumerate(lines, 1):
            where = f'{spec}:{number}'
            if not raw.strip() or raw.lstrip().startswith('#'):
                continue
            text = raw.strip()
            if not raw.startswith(' '):
                target, event = None, None
                if text.startswith('import '):
                    imports.append((text[7:].strip(), where))
                elif text.startswith('area '):
                    words = text.split()
                    area = Area(words[1], 'core' in words[2:])
                    areas.append(area)
                elif area is None:
                    fail(where, 'declarations must follow an area line')
                elif text.startswith('type '):
                    target = parse_type_line(text, where, area)
                elif text.startswith('prop ') or text.startswith('fn '):
                    keyword, rest = text.split(' ', 1)
                    target = parse_member(keyword, rest, where)
                    area.members.append(target)
                elif text.startswith('event '):
                    head, doc = split_doc(text[6:])
                    if ' = ' not in head:
                        fail(where, 'an event needs = <java class>')
                    name, rest = head.split(' = ', 1)
                    words = rest.split()
                    java = words[0]
                    event = Event(name.strip(), java, java.rsplit('.', 1)[1], where, doc=doc)
                    supertype = None
                    i = 1
                    while i < len(words):
                        word = words[i]
                        if word == 'cancellable':
                            event.cancellable = True
                        elif word == 'extends':
                            i += 1
                            supertype = words[i]
                        elif word in FLAGS_THREADING:
                            event.threading = FLAGS_THREADING[word]
                        else:
                            fail(where, 'unknown event option ' + word)
                        i += 1
                    if event.type_name not in TYPES:
                        supers = []
                        if supertype:
                            if supertype not in TYPES:
                                fail(where, 'unknown supertype ' + supertype)
                            supers.append(supertype)
                        if event.cancellable and not any(is_subtype(s, 'Cancellable') for s in supers):
                            supers.insert(0, 'Cancellable')
                        TYPES[event.type_name] = TypeInfo(event.type_name, 'GeneratedTypes.' + upper_snake(event.type_name),
                                                          java, supertypes=supers, where=where,
                                                          doc='The event object of ' + event.name + ' handlers.')
                        area.types.append(TYPES[event.type_name])
                    elif supertype:
                        fail(where, 'event type ' + event.type_name + ' already exists; cannot extend it here')
                    area.events.append(event)
                    target = event
                else:
                    fail(where, 'unknown directive: ' + text)
                continue
            # Indented lines.
            key = text.split(':', 1)[0] if ':' in text else ''
            if key in ('get', 'set', 'do', 'codec', 'ex', 'details'):
                value = text.split(':', 1)[1].strip()
                indent = len(raw) - len(raw.lstrip(' '))
                if event is not None and indent <= 2 and key in ('ex', 'details'):
                    target = event
                if target is None:
                    fail(where, key + ': without a declaration')
                if key == 'ex':
                    target.examples.append(value.replace('\\n', '\n'))
                elif key == 'details':
                    target.details = (target.details + ' ' + value).strip()
                elif key == 'codec':
                    if not isinstance(target, TypeInfo):
                        fail(where, 'codec: belongs to a type')
                    target.codec = value
                else:
                    if not isinstance(target, Member):
                        fail(where, key + ': belongs to a property or function')
                    setattr(target, 'body' if key == 'do' else key, value)
                continue
            if event is None:
                fail(where, 'unexpected indented line: ' + text)
            if text.startswith('var '):
                head, doc = split_doc(text[4:])
                if ' = ' not in head:
                    fail(where, 'an event variable needs = <expression>')
                decl, expr = head.split(' = ', 1)
                name, type_text = decl.split(':', 1)
                var = EventVar(name.strip(), TypeRef(type_text), expr.strip(), doc)
                var.type.check(where)
                event.vars.append(var)
                target = event
            elif text.startswith('prop ') or text.startswith('fn '):
                keyword, rest = text.split(' ', 1)
                target = parse_member(keyword, rest, where, owner_override=event.type_name)
                area.members.append(target)
            else:
                fail(where, 'unexpected line in an event: ' + text)
    return areas, imports


# ============================================================================ checks

def check(areas):
    names = {}
    for area in areas:
        for m in area.members:
            if m.kind == 'prop' and m.get is None:
                fail(m.where, 'property without get:')
            if m.kind == 'prop' and m.mutable and m.set is None:
                fail(m.where, 'writable property without set:')
            if m.kind == 'prop' and not m.mutable and m.set is not None:
                fail(m.where, 'set: on a read-only property (add rw)')
            if m.kind == 'fn' and m.body is None:
                fail(m.where, 'function without do:')
            if area.core:
                used = [m.type] + [p.type for p in m.params] + ([TypeRef(m.owner)] if m.owner else [])
                for t in used:
                    b = t.base
                    if b in TYPES and not TYPES[b].core:
                        fail(m.where, 'core areas can only use core types, not ' + b)
            if m.owner and m.owner not in TYPES:
                fail(m.where, 'unknown owner ' + m.owner)
            other_kind = 'fn' if m.kind == 'prop' else 'prop'
            for (owner, name, kind, _), where in names.items():
                if owner == m.owner and name == m.name and kind == other_kind:
                    fail(m.where, m.name + ' is both a property and a function (see ' + where + ')')
            signature = (m.owner, m.name, m.kind, tuple(p.type.text for p in m.params))
            if signature in names:
                fail(m.where, 'duplicate of ' + names[signature])
            names[signature] = m.where
        for e in area.events:
            if area.core:
                fail(e.where, 'core areas cannot declare events')


# ============================================================================ keys

def strip_java_comments(text):
    text = re.sub(r'/\*.*?\*/', lambda m: ' ' * len(m.group(0)), text, flags=re.S)
    return re.sub(r'//[^\n]*', '', text)


def enum_constants(text, enum_name=None):
    """(constant, first string argument, '' for null, or None) of an enum in a Java source."""
    text = strip_java_comments(text)
    pattern = r'\benum\s+' + (re.escape(enum_name) if enum_name else r'\w+') + r'\b[^{]*\{'
    m = re.search(pattern, text)
    if not m:
        raise SpecError('No enum ' + (enum_name or '') + ' found')
    i = m.end()
    depth = 0
    constants = []
    current = ''
    while i < len(text):
        c = text[i]
        if c == '"':
            end = text.index('"', i + 1)
            while text[end - 1] == '\\':
                end = text.index('"', end + 1)
            current += text[i:end + 1]
            i = end + 1
            continue
        if c in '({':
            depth += 1
        elif c in ')}':
            if depth == 0:
                constants.append(current)
                break
            depth -= 1
        if depth == 0 and c in ',;':
            constants.append(current)
            current = ''
            if c == ';':
                break
        else:
            current += c
        i += 1
    result = []
    for item in constants:
        item = re.sub(r'@\w+(\([^)]*\))?', '', item).strip()
        m = re.match(r'([A-Z][A-Z0-9_]*)\s*(\((.*))?', item, re.S)
        if not m:
            continue
        args = m.group(3) or ''
        string = re.match(r'\s*"([^"]*)"', args)
        null_first = re.match(r'\s*null\b', args)
        result.append((m.group(1), string.group(1) if string else ('' if null_first else None)))
    return result


def extract_keys(spec, sources):
    kind, _, rest = spec.partition(':')
    if kind == 'list':
        return [(name, 'minecraft:' + name.lower()) for name in rest.split(',')]
    path, _, detail = rest.partition(':' if kind == 'fields' else '#')
    with open(os.path.join(sources, path), encoding='utf-8') as source:
        text = source.read()
    pairs = []
    if kind == 'enum':
        for name, key in enum_constants(text, detail or None):
            if name.startswith('LEGACY_') or key == '':
                continue
            key = key or name.lower()
            pairs.append((name, key if ':' in key else 'minecraft:' + key))
        return pairs
    if kind == 'fields':
        for m in re.finditer(r'\b([A-Z][A-Z0-9_]*)\s*=\s*' + re.escape(detail) + r'\(\s*(?:\d+\s*,\s*)?"([^"]+)"', text):
            key = m.group(2)
            pairs.append((m.group(1), key if ':' in key else 'minecraft:' + key))
        return pairs
    raise SpecError('Unknown key source ' + spec)


def lookup_expression(info):
    kind, _, rest = info.lookup.partition(':')
    if kind == 'enum':
        return 'PaperKeys.enumConstants(' + info.java + '.class)'
    if kind == 'keyed-enum':
        return 'PaperKeys.keyedEnum(' + info.java + '.class)'
    if kind == 'registry':
        return 'PaperKeys.registry(io.papermc.paper.registry.RegistryKey.' + rest + ')'
    raise SpecError(info.where + ': unknown lookup ' + info.lookup)


# ============================================================================ Java output

def java_string(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'


def documentation(doc, details, examples):
    return ('new Documentation(' + java_string(doc) + ', ' + java_string(details) + ', List.of('
            + ', '.join(java_string(e) for e in examples) + '), "' + SINCE + '")')


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if os.path.exists(path):
        with open(path, encoding='utf-8') as old:
            if old.read() == content:
                return
    with open(path, 'w', encoding='utf-8', newline='\n') as out:
        out.write(content)


def assign_constants(areas):
    for area in areas:
        taken = set()
        for event in area.events:
            event.constant = upper_snake(event.name) + '_EVENT'
            taken.add(event.constant)
        for member in area.members:
            base = upper_snake((member.owner + '_' if member.owner else '') + member.name)
            name, n = base, 2
            while name in taken:
                name = base + '_' + str(n)
                n += 1
            taken.add(name)
            member.constant = name


def threading_index(member):
    """Invocable parameter index of the threading target (the receiver is 0 for members)."""
    offset = 1 if member.owner else 0
    if member.thread_param is None:
        return 0
    return offset + [p.name for p in member.params].index(member.thread_param)


def declaration(member):
    doc = '.documentation(' + documentation(member.doc, member.details, member.examples) + ')'
    owner = TYPES[member.owner].constant if member.owner else None
    if member.kind == 'prop':
        text = ('PropertyDeclaration.member(' + owner + ', ' + java_string(member.name) + ', ' if owner
                else 'PropertyDeclaration.global(' + java_string(member.name) + ', ') + member.type.constant() + ')'
        if member.mutable:
            text += '.mutable()'
        if member.threading != 'ANY':
            if member.owner or member.threading in ('GLOBAL', 'ASYNC'):
                text += '.getterThreading(ThreadingRequirement.' + member.threading + ')'
                if member.mutable:
                    text += '.setterThreading(ThreadingRequirement.' + member.threading + ')'
        if member.mutable:
            text += '.setterEffects(Effect.MODIFIES_WORLD)'
        if member.effect and member.effect != 'MODIFIES_WORLD':
            text += '.getterEffects(Effect.' + member.effect + ')'
        return text + '\n            ' + doc + '.build()'
    text = ('FunctionDeclaration.method(' + owner + ', ' + java_string(member.name) + ')' if owner
            else 'FunctionDeclaration.global(' + java_string(member.name) + ')')
    for p in member.params:
        text += '.parameter(' + java_string(p.name) + ', ' + p.type.constant() + ')'
    if member.type.base != 'void':
        text += '.returns(' + member.type.constant() + ')'
    if member.effect:
        text += '.effects(Effect.' + member.effect + ')'
    if member.threading in ('ENTITY', 'REGION'):
        text += '.threading(ThreadingRequirement.' + member.threading + ', ' + str(threading_index(member)) + ')'
    elif member.threading != 'ANY':
        text += '.threading(ThreadingRequirement.' + member.threading + ')'
    return text + '\n            ' + doc + '.build()'


def write_types(areas, key_tables):
    ordered = []
    seen = set()

    def visit(info):
        if info.name in seen or not info.new:
            return
        seen.add(info.name)
        for s in info.supertypes:
            visit(TYPES[s])
        ordered.append(info)

    for area in areas:
        for info in area.types:
            visit(info)
    lines = [HEADER, 'package ' + STDLIB_PACKAGE + ';', '',
             'import dev.tachyonscript.api.doc.Documentation;',
             'import dev.tachyonscript.api.registry.KeyTable;',
             'import dev.tachyonscript.api.type.ClassType;',
             'import dev.tachyonscript.stdlib.MinecraftTypes;', '',
             'import java.util.LinkedHashMap;', 'import java.util.List;', 'import java.util.Map;', '',
             '/** Types of the generated standard library, supertypes before subtypes. */',
             'public final class GeneratedTypes {', '']
    for info in ordered:
        text = ('    // ' + info.where + '\n    public static final ClassType ' + upper_snake(info.name)
                + ' = ClassType.builder(' + java_string(info.name) + ')')
        if info.supertypes:
            text += '.supertypes(' + ', '.join(TYPES[s].constant.replace('GeneratedTypes.', '') for s in info.supertypes) + ')'
        if info.keyed:
            text += '.keyed()'
        if info.storable:
            text += '.storable()'
        text += ('\n            .documentation(new Documentation(' + java_string(info.doc) + ', ' + java_string(info.details)
                 + ', List.of(' + ', '.join(java_string(e) for e in info.examples) + '), "' + SINCE + '")).build();')
        lines.append(text)
    lines += ['',
              '    /** Every generated type, supertypes first (registration order). */',
              '    public static final List<ClassType> ALL = List.of(' + ', '.join(upper_snake(i.name) for i in ordered) + ');',
              '', '    private GeneratedTypes() {', '    }', '',
              '    /**',
              '     * The constant tables of the keyed types, from the Paper API TachyonScript was built with.',
              '     * On a server, the platform replaces them with the contents of the live registries.',
              '     */',
              '    public static Map<ClassType, KeyTable> keyTables() {',
              '        Map<ClassType, KeyTable> tables = new LinkedHashMap<>();']
    for name, resource in key_tables.items():
        lines.append('        tables.put(' + TYPES[name].constant.replace('GeneratedTypes.', '') + ', GeneratedKeys.load('
                     + java_string(resource) + '));')
    lines += ['        return tables;', '    }', '}', '']
    write(os.path.join(STDLIB_OUT, 'GeneratedTypes.java'), '\n'.join(lines))
    write(os.path.join(STDLIB_OUT, 'GeneratedKeys.java'), '\n'.join([
        HEADER, 'package ' + STDLIB_PACKAGE + ';', '',
        'import dev.tachyonscript.api.registry.KeyTable;', '',
        'import java.io.BufferedReader;', 'import java.io.IOException;', 'import java.io.InputStream;',
        'import java.io.InputStreamReader;', 'import java.io.UncheckedIOException;',
        'import java.nio.charset.StandardCharsets;', 'import java.util.LinkedHashMap;', 'import java.util.Map;', '',
        '/** Loads the constant tables ({@code NAME namespace:key} per line) shipped with the standard library. */',
        'final class GeneratedKeys {', '', '    private GeneratedKeys() {', '    }', '',
        '    static KeyTable load(String resource) {',
        '        Map<String, String> entries = new LinkedHashMap<>();',
        '        InputStream raw = GeneratedKeys.class.getResourceAsStream("/dev/tachyonscript/stdlib/keys/" + resource);',
        '        if (raw == null) {',
        '            throw new UncheckedIOException(new IOException("Missing constant table " + resource));',
        '        }',
        '        try (BufferedReader reader = new BufferedReader(new InputStreamReader(raw, StandardCharsets.UTF_8))) {',
        '            String line;',
        '            while ((line = reader.readLine()) != null) {',
        "                int space = line.indexOf(' ');",
        '                if (space > 0) {',
        '                    entries.put(line.substring(0, space), line.substring(space + 1));',
        '                }',
        '            }',
        '        } catch (IOException e) {',
        '            throw new UncheckedIOException(e);',
        '        }',
        '        return KeyTable.of(entries);',
        '    }', '}', ''
    ]))
    return ordered


def write_api(area):
    cls = area.name + 'Api'
    lines = [HEADER, 'package ' + STDLIB_PACKAGE + ';', '',
             'import dev.tachyonscript.api.declaration.Effect;',
             'import dev.tachyonscript.api.declaration.EventDeclaration;',
             'import dev.tachyonscript.api.declaration.FunctionDeclaration;',
             'import dev.tachyonscript.api.declaration.PropertyDeclaration;',
             'import dev.tachyonscript.api.declaration.ThreadingRequirement;',
             'import dev.tachyonscript.api.doc.Documentation;',
             'import dev.tachyonscript.api.registry.SymbolRegistry;',
             'import dev.tachyonscript.api.type.Types;',
             'import dev.tachyonscript.stdlib.MinecraftTypes;', '',
             'import java.util.List;', '',
             '/** Declarations of the standard library area ' + area.name + '. */',
             '@SuppressWarnings("unused")',
             'public final class ' + cls + ' {', '']
    for event in area.events:
        text = ('    public static final EventDeclaration ' + event.constant + ' = EventDeclaration.builder('
                + java_string(event.name) + ', ' + TYPES[event.type_name].constant + ')')
        for var in event.vars:
            text += '\n            .variable(' + java_string(var.name) + ', ' + var.type.constant() + ', ' + java_string(var.doc) + ')'
        if event.cancellable:
            text += '\n            .cancellable()'
        text += '\n            .threading(ThreadingRequirement.' + event.threading + ')'
        text += '\n            .documentation(' + documentation(event.doc, event.details, event.examples) + ').build();'
        lines.append('    // ' + event.where)
        lines.append(text)
    for member in area.members:
        java_type = 'PropertyDeclaration' if member.kind == 'prop' else 'FunctionDeclaration'
        lines.append('    // ' + member.where)
        lines.append('    public static final ' + java_type + ' ' + member.constant + ' = ' + declaration(member) + ';')
    props = [m.constant for m in area.members if m.kind == 'prop']
    fns = [m.constant for m in area.members if m.kind == 'fn']
    lines += ['',
              '    public static final List<PropertyDeclaration> PROPERTIES = List.of(' + ', '.join(props) + ');',
              '    public static final List<FunctionDeclaration> FUNCTIONS = List.of(' + ', '.join(fns) + ');',
              '    public static final List<EventDeclaration> EVENTS = List.of(' + ', '.join(e.constant for e in area.events) + ');',
              '', '    private ' + cls + '() {', '    }', '',
              '    /** Registers the members and events of this area (its types are registered first, separately). */',
              '    public static void register(SymbolRegistry.Builder builder) {',
              '        PROPERTIES.forEach(builder::property);',
              '        FUNCTIONS.forEach(builder::function);',
              '        EVENTS.forEach(builder::event);',
              '    }', '}', '']
    write(os.path.join(STDLIB_OUT, cls + '.java'), '\n'.join(lines))


def self_expr(text):
    """Replaces $ (the receiver) with self."""
    return re.sub(r'\$(?![A-Za-z0-9_{])', 'self', text)


def is_block(code):
    code = code.strip()
    return code.startswith('{') and code.endswith('}')


def receiver_lines(member):
    lines = []
    offset = 0
    if member.owner:
        lines.append(TypeRef(member.owner).java() + ' self = ' + TypeRef(member.owner).read(0) + ';')
        offset = 1
    for i, p in enumerate(member.params):
        lines.append(p.type.java() + ' ' + p.name + ' = ' + p.type.read(i + offset) + ';')
    return lines


def wrapped(member, code, returns):
    """Java statements running code on the thread the member requires."""
    code = self_expr(code).strip()
    kind = member.threading
    target = (member.thread_param or 'self') if kind in ('ENTITY', 'REGION') else None
    if kind in ('ENTITY', 'REGION', 'GLOBAL'):
        body = code if is_block(code) else code.rstrip(';')
        if not returns:
            call = {'ENTITY': 'forEntity', 'REGION': 'forRegion', 'GLOBAL': 'global'}[kind]
            return ['ctx.' + call + '(' + (target + ', ' if target else '') + '() -> ' + body + ');']
        if member.effect == 'MODIFIES_WORLD':
            call = {'ENTITY': 'callEntity', 'REGION': 'callRegion', 'GLOBAL': 'callGlobal'}[kind]
            return ['return ctx.' + call + '(' + (target + ', ' if target else '') + '() -> ' + body + ');']
    if is_block(code):
        return [code[1:-1].strip()]
    if returns:
        return ['return ' + code.rstrip(';') + ';']
    return [code if code.endswith(';') else code + ';']


def binding(api, member):
    ref = api + '.' + member.constant
    out = ['        // ' + member.where]
    setup = receiver_lines(member)
    if member.kind == 'prop':
        getter = Member('prop', member.owner, member.name, [], member.type, member.where)
        out.append('        b.bindGetter(' + ref + ', (NativeFunction.' + member.type.shape() + ') a -> {')
        out += ['            ' + line for line in setup]
        out += ['            ' + line for line in wrapped(getter, member.get, True)]
        out.append('        });')
        if member.mutable:
            index = 1 if member.owner else 0
            out.append('        b.bindSetter(' + ref + ', a -> {')
            out += ['            ' + line for line in setup]
            out.append('            ' + member.type.java() + ' v = ' + member.type.read(index) + ';')
            out += ['            ' + line for line in wrapped(member, member.set, False)]
            out.append('        });')
        return out
    returns = member.type.base != 'void'
    out.append('        b.bind(' + ref + ', (NativeFunction.' + member.type.shape() + ') a -> {')
    out += ['            ' + line for line in setup]
    out += ['            ' + line for line in wrapped(member, member.body, returns)]
    out.append('        });')
    return out


def write_bindings(area, imports):
    cls = area.name + 'Bindings'
    api = area.name + 'Api'
    if area.core:
        package, directory = STDLIB_PACKAGE, STDLIB_OUT
        header_imports = ['import dev.tachyonscript.api.natives.NativeFunction;',
                          'import dev.tachyonscript.api.natives.ScriptError;',
                          'import dev.tachyonscript.api.registry.Bindings;',
                          'import dev.tachyonscript.stdlib.support.Core;']
        signature = '    public static void bind(Bindings.Builder b) {'
    else:
        package, directory = PAPER_PACKAGE, PAPER_OUT
        header_imports = ['import dev.tachyonscript.api.declaration.EventDeclaration;',
                          'import dev.tachyonscript.api.natives.NativeFunction;',
                          'import dev.tachyonscript.api.natives.ScriptError;',
                          'import dev.tachyonscript.api.registry.Bindings;',
                          'import dev.tachyonscript.platform.paper.PaperContext;',
                          'import dev.tachyonscript.stdlib.generated.' + api + ';'] + ['import ' + i + ';' for i in imports]
        signature = '    public static void bind(Bindings.Builder b, PaperContext ctx) {'
    lines = [HEADER, 'package ' + package + ';', ''] + header_imports + [
        '', '/** Implementations of the standard library area ' + area.name + '. */',
        SUPPRESS, 'public final class ' + cls + ' {', '', '    private ' + cls + '() {', '    }', '', signature]
    for event in area.events:
        java = TYPES[event.type_name].java
        for var in event.vars:
            lines.append('        // ' + event.where + ' ' + var.name)
            lines.append('        b.bind(' + api + '.' + event.constant + '.variable(' + java_string(var.name)
                         + ').orElseThrow(), (NativeFunction.' + var.type.shape() + ') a -> {')
            lines.append('            ' + java + ' self = (' + java + ') a.getRef(0);')
            lines.append('            return ' + self_expr(var.expr) + ';')
            lines.append('        });')
    for member in area.members:
        lines += binding(api, member)
    lines.append('    }')
    if not area.core:
        lines += ['', '    /** The Bukkit event class of each event of this area. */',
                  '    public static void events(java.util.Map<EventDeclaration, Class<? extends org.bukkit.event.Event>> classes) {']
        for event in area.events:
            lines.append('        classes.put(' + api + '.' + event.constant + ', ' + event.java + '.class);')
        lines.append('    }')
    lines += ['}', '']
    write(os.path.join(directory, cls + '.java'), '\n'.join(lines))


def write_library(areas, ordered, keyed):
    lines = [HEADER, 'package ' + STDLIB_PACKAGE + ';', '',
             'import dev.tachyonscript.api.registry.Bindings;',
             'import dev.tachyonscript.api.registry.SymbolRegistry;', '',
             '/** Registers and binds the generated part of the standard library. */',
             'public final class GeneratedLibrary {', '', '    private GeneratedLibrary() {', '    }', '',
             '    /** Registers the generated types (after the hand-written ones they extend). */',
             '    public static void registerTypes(SymbolRegistry.Builder builder) {',
             '        GeneratedTypes.ALL.forEach(builder::type);',
             '    }', '',
             '    /** Registers the generated members, events and constant tables. */',
             '    public static void registerMembers(SymbolRegistry.Builder builder) {']
    for area in areas:
        lines.append('        ' + area.name + 'Api.register(builder);')
    lines += ['        GeneratedTypes.keyTables().forEach(builder::keys);', '    }', '',
              '    /** Implementations that need no server (the core areas). */',
              '    public static void bindCore(Bindings.Builder builder) {']
    for info in ordered:
        if info.core:
            lines.append('        builder.bindType(' + info.constant + ', ' + info.java + '.class);')
            if info.codec:
                lines.append('        builder.bindCodec(' + info.constant + ', ' + info.codec + ');')
    for area in areas:
        if area.core:
            lines.append('        ' + area.name + 'Bindings.bind(builder);')
    lines += ['    }', '}', '']
    write(os.path.join(STDLIB_OUT, 'GeneratedLibrary.java'), '\n'.join(lines))

    paper = [HEADER, 'package ' + PAPER_PACKAGE + ';', '',
             'import dev.tachyonscript.api.declaration.EventDeclaration;',
             'import dev.tachyonscript.api.registry.Bindings;',
             'import dev.tachyonscript.api.registry.SymbolRegistry;',
             'import dev.tachyonscript.platform.paper.PaperContext;',
             'import dev.tachyonscript.platform.paper.lib.Codecs;',
             'import dev.tachyonscript.platform.paper.lib.PaperKeys;',
             'import dev.tachyonscript.stdlib.generated.GeneratedTypes;', '',
             'import java.util.Map;', '',
             '/** Binds the generated part of the standard library on Paper. */',
             SUPPRESS,
             'public final class GeneratedBindings {', '', '    private GeneratedBindings() {', '    }', '',
             '    public static void bind(Bindings.Builder b, PaperContext ctx) {']
    for info in ordered:
        if not info.core and info.java:
            paper.append('        b.bindType(' + info.constant + ', ' + info.java + '.class);')
            if info.codec:
                paper.append('        b.bindCodec(' + info.constant + ', ' + info.codec + ');')
    for info in keyed:
        paper.append('        b.bindKeys(' + info.constant + ', ' + lookup_expression(info) + ');')
    for area in areas:
        if not area.core:
            paper.append('        ' + area.name + 'Bindings.bind(b, ctx);')
    paper += ['    }', '',
              '    /** The Bukkit event class of every generated event. */',
              '    public static void events(Map<EventDeclaration, Class<? extends org.bukkit.event.Event>> classes) {']
    for area in areas:
        if not area.core:
            paper.append('        ' + area.name + 'Bindings.events(classes);')
    paper += ['    }', '',
              '    /** Replaces the built-in constant tables with the contents of the running server\'s registries. */',
              '    public static void liveKeys(SymbolRegistry.Builder builder) {']
    for info in keyed:
        paper.append('        PaperKeys.live(builder, ' + info.constant + ', ' + lookup_expression(info) + ');')
    paper += ['    }', '}', '']
    write(os.path.join(PAPER_OUT, 'GeneratedBindings.java'), '\n'.join(paper))


def remove_stale(directory, keep):
    if not os.path.isdir(directory):
        return
    for name in os.listdir(directory):
        if name.endswith('.java') and name not in keep:
            os.remove(os.path.join(directory, name))


def main():
    parser = argparse.ArgumentParser(description='Generates the TachyonScript standard library from its specifications.')
    parser.add_argument('--paper-sources', help='folder with the Paper API sources (org/bukkit/...), for constant tables')
    arguments = parser.parse_args()
    try:
        areas, imports = read_specs()
        check(areas)
        assign_constants(areas)
        simple = {}
        for fqn, where in imports:
            name = fqn.rsplit('.', 1)[1]
            if name in simple and simple[name] != fqn:
                fail(where, 'import ' + fqn + ' clashes with ' + simple[name])
            simple[name] = fqn
        import_list = sorted(set(fqn for fqn, _ in imports))
        keyed = [info for info in TYPES.values() if info.new and info.keyed]
        key_tables = {}
        for info in keyed:
            resource = info.name.lower() + '.txt'
            key_tables[info.name] = resource
            if arguments.paper_sources:
                pairs = extract_keys(info.keyed, arguments.paper_sources)
                if not pairs:
                    fail(info.where, 'no constants found for ' + info.keyed)
                write(os.path.join(KEYS_OUT, resource), ''.join(n + ' ' + k + '\n' for n, k in pairs))
            elif not os.path.exists(os.path.join(KEYS_OUT, resource)):
                fail(info.where, 'no constant table yet; run with --paper-sources')
        ordered = write_types(areas, key_tables)
        for area in areas:
            write_api(area)
            write_bindings(area, import_list)
        write_library(areas, ordered, keyed)
        stdlib_files = {'GeneratedTypes.java', 'GeneratedKeys.java', 'GeneratedLibrary.java'}
        paper_files = {'GeneratedBindings.java'}
        for area in areas:
            stdlib_files.add(area.name + 'Api.java')
            (stdlib_files if area.core else paper_files).add(area.name + 'Bindings.java')
        remove_stale(STDLIB_OUT, stdlib_files)
        remove_stale(PAPER_OUT, paper_files)
    except SpecError as e:
        print('error: ' + str(e), file=sys.stderr)
        return 1
    members = sum(len(a.members) for a in areas)
    events = sum(len(a.events) for a in areas)
    types = sum(1 for t in TYPES.values() if t.new)
    print(f'{len(areas)} areas, {types} types ({len(keyed)} keyed), {members} members, {events} events')
    return 0


if __name__ == '__main__':
    sys.exit(main())
