package dev.tachyonscript.cli;

import dev.tachyonscript.api.declaration.EventDeclaration;
import dev.tachyonscript.api.declaration.EventVariable;
import dev.tachyonscript.api.declaration.FunctionDeclaration;
import dev.tachyonscript.api.declaration.Parameter;
import dev.tachyonscript.api.declaration.PropertyDeclaration;
import dev.tachyonscript.api.doc.Deprecation;
import dev.tachyonscript.api.doc.Documentation;
import dev.tachyonscript.api.registry.SymbolRegistry;
import dev.tachyonscript.api.type.ClassType;
import dev.tachyonscript.api.type.Type;
import dev.tachyonscript.api.type.Types;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Optional;

/**
 * Generates the Markdown reference of everything scripts can use from a registry, so that
 * the documentation is derived from the same declarations the compiler checks against.
 * {@code docs/language/reference.md} is this output; a test keeps it up to date.
 */
final class ReferenceGenerator {

    private final SymbolRegistry registry;
    private final StringBuilder out = new StringBuilder();

    private ReferenceGenerator(SymbolRegistry registry) {
        this.registry = registry;
    }

    static String generate(SymbolRegistry registry) {
        return new ReferenceGenerator(registry).render();
    }

    private String render() {
        out.append("# Standard library reference\n\n")
                .append("<!-- Generated by `tys docs` from the standard library declarations. Do not edit by hand:\n")
                .append("     run `./gradlew -q :tachyon-cli:run --args=docs > docs/language/reference.md`. -->\n\n")
                .append("Everything below is checked by the compiler: using a name that is not listed here, or\n")
                .append("with the wrong types, is a compile error with a suggestion.\n\n")
                .append("* [Events](#events)\n* [Global functions and properties](#global-functions-and-properties)\n")
                .append("* [Types](#types)\n\n");
        events();
        globals();
        types();
        return out.toString();
    }

    // ================================================================= events

    private void events() {
        out.append("## Events\n\n")
                .append("A handler is written `event <name> { ... }`. The variables below are available in the\n")
                .append("handler; `event` is the event object itself.\n\n");
        for (EventDeclaration event : registry.events()) {
            out.append("### `").append(event.name()).append("`\n\n");
            documentation(event.documentation(), event.deprecation());
            if (!event.variables().isEmpty()) {
                out.append("| Variable | Type | Description |\n|---|---|---|\n");
                for (EventVariable variable : event.variables()) {
                    row("`" + variable.name() + "`", type(variable.type()), variable.documentation().summary());
                }
                out.append('\n');
            }
            out.append("`event` is a ").append(typeLink(event.eventType()));
            out.append(event.isCancellable() ? "; the event can be cancelled with `event.cancel()`.\n\n" : ".\n\n");
            examples(event.documentation());
        }
    }

    // ================================================================= globals

    private void globals() {
        out.append("## Global functions and properties\n\n");
        List<String> rootFunctions = new ArrayList<>();
        List<String> namespaces = new ArrayList<>();
        for (String member : registry.namespaceMembers("")) {
            if (registry.isNamespace(member)) {
                namespaces.add(member);
            }
            if (!registry.functions(member).isEmpty() || registry.globalProperty(member).isPresent()) {
                rootFunctions.add(member);
            }
        }
        if (!rootFunctions.isEmpty()) {
            out.append("### Top level\n\n");
            memberTable(rootFunctions);
        }
        for (String namespace : namespaces) {
            namespace(namespace);
        }
    }

    private void namespace(String namespace) {
        List<String> members = new ArrayList<>();
        List<String> nested = new ArrayList<>();
        for (String simple : registry.namespaceMembers(namespace)) {
            String qualified = namespace + "." + simple;
            if (!registry.functions(qualified).isEmpty() || registry.globalProperty(qualified).isPresent()) {
                members.add(qualified);
            }
            if (registry.isNamespace(qualified)) {
                nested.add(qualified);
            }
        }
        if (!members.isEmpty()) {
            out.append("### `").append(namespace).append("`\n\n");
            memberTable(members);
        }
        for (String inner : nested) {
            namespace(inner);
        }
    }

    private void memberTable(List<String> qualifiedNames) {
        out.append("| Name | Type | Description |\n|---|---|---|\n");
        for (String name : qualifiedNames) {
            Optional<PropertyDeclaration> property = registry.globalProperty(name);
            property.ifPresent(p -> row("`" + name + "`" + (p.isMutable() ? " (read/write)" : ""), type(p.type()),
                    summary(p.documentation(), p.deprecation())));
            for (FunctionDeclaration function : registry.functions(name)) {
                row("`" + name + signature(function) + "`", type(function.returnType()),
                        summary(function.documentation(), function.deprecation()));
            }
        }
        out.append('\n');
    }

    // ================================================================= types

    private void types() {
        out.append("## Types\n\n")
                .append("Built into the language: `int`, `long`, `float`, `double`, `bool`, `Duration`, `List<T>`,\n")
                .append("and `T?` (a `T` or `null`); see [Types](types.md).\n\n");
        for (ClassType type : registry.types()) {
            out.append("### ").append(type.name()).append("\n\n");
            documentation(type.documentation(), Optional.empty());
            if (!type.supertypes().isEmpty()) {
                List<String> supertypes = new ArrayList<>();
                for (ClassType supertype : type.supertypes()) {
                    supertypes.add(typeLink(supertype));
                }
                out.append("Has all members of ").append(String.join(" and ", supertypes)).append(".\n\n");
            }
            List<String> rows = new ArrayList<>();
            for (String name : registry.declaredMemberNames(type)) {
                registry.declaredProperty(type, name).ifPresent(p -> rows.add(rowText("`" + name + "`"
                        + (p.isMutable() ? " (read/write)" : ""), type(p.type()), summary(p.documentation(), p.deprecation()))));
                for (FunctionDeclaration method : registry.declaredMethods(type, name)) {
                    rows.add(rowText("`" + name + signature(method) + "`", type(method.returnType()),
                            summary(method.documentation(), method.deprecation())));
                }
            }
            if (!rows.isEmpty()) {
                out.append("| Member | Type | Description |\n|---|---|---|\n");
                rows.forEach(out::append);
                out.append('\n');
            }
        }
    }

    // ================================================================= helpers

    private static String signature(FunctionDeclaration function) {
        List<String> parameters = new ArrayList<>();
        List<Parameter> all = function.parameters();
        for (Parameter parameter : all) {
            parameters.add(parameter.name() + ": " + parameter.type().displayName());
        }
        return "(" + String.join(", ", parameters) + ")";
    }

    private String type(Type type) {
        if (type == Types.VOID) {
            return "`void`";
        }
        return "`" + type.displayName() + "`";
    }

    private String typeLink(ClassType type) {
        if (registry.type(type.name()).isEmpty() || type == Types.ANY) {
            return "`" + type.name() + "`";
        }
        return "[`" + type.name() + "`](#" + type.name().toLowerCase(Locale.ROOT) + ")";
    }

    private void documentation(Documentation documentation, Optional<Deprecation> deprecation) {
        if (!documentation.summary().isEmpty()) {
            out.append(documentation.summary()).append("\n\n");
        }
        if (!documentation.details().isEmpty()) {
            out.append(documentation.details()).append("\n\n");
        }
        deprecation.ifPresent(d -> out.append("**Deprecated.** ").append(d.message()).append("\n\n"));
    }

    private void examples(Documentation documentation) {
        for (String example : documentation.examples()) {
            out.append("```tys\n").append(example.strip()).append("\n```\n\n");
        }
    }

    private static String summary(Documentation documentation, Optional<Deprecation> deprecation) {
        return deprecation.map(d -> "**Deprecated:** " + d.message() + " ").orElse("") + documentation.summary();
    }

    private void row(String name, String type, String description) {
        out.append(rowText(name, type, description));
    }

    private static String rowText(String name, String type, String description) {
        return "| " + name + " | " + type + " | " + description.replace("|", "\\|").replace("\n", " ") + " |\n";
    }
}
